// AUTO-GENERATED by src/analytical/stokes.py — DO NOT EDIT BY HAND
#pragma once
#include <cmath>
#include <petscsys.h>

// ============================================================================
// FLOW EQUATIONS: Various formulations with manufactured solutions
// Solution: Taylor-Green vortex (2D) + Poiseuille flow (2D)
// nu = 1.0
// ============================================================================
namespace STOKES {

namespace FUNC_2D {
using VELOCITY_EXACT  = PetscScalar (*)(PetscScalar, PetscScalar, PetscScalar);
using PRESSURE_EXACT  = PetscScalar (*)(PetscScalar, PetscScalar, PetscScalar);
using FORCE           = PetscScalar (*)(PetscScalar, PetscScalar, PetscScalar);
} // namespace FUNC_2D

namespace TAYLOR_GREEN_2D {
static inline PetscScalar u_exact(PetscScalar x, PetscScalar y, PetscScalar t) {
  return (PetscScalar)(-std::exp(-2.0*std::pow(M_PI, 2)*t)*std::sin(M_PI*y)*std::cos(M_PI*x));
}

static inline PetscScalar v_exact(PetscScalar x, PetscScalar y, PetscScalar t) {
  return (PetscScalar)(std::exp(-2.0*std::pow(M_PI, 2)*t)*std::sin(M_PI*x)*std::cos(M_PI*y));
}

static inline PetscScalar p_exact(PetscScalar x, PetscScalar y, PetscScalar t) {
  return (PetscScalar)(-1.0/4.0*(std::cos(2*M_PI*x) + std::cos(2*M_PI*y))*std::exp(-4.0*std::pow(M_PI, 2)*t));
}

static inline PetscScalar fx_heat(PetscScalar x, PetscScalar y, PetscScalar t) {
  return (PetscScalar)(0);
}

static inline PetscScalar fy_heat(PetscScalar x, PetscScalar y, PetscScalar t) {
  return (PetscScalar)(0);
}

static inline PetscScalar fx_stokes(PetscScalar x, PetscScalar y, PetscScalar t) {
  return (PetscScalar)((1.0/2.0)*M_PI*std::exp(-4.0*std::pow(M_PI, 2)*t)*std::sin(2*M_PI*x));
}

static inline PetscScalar fy_stokes(PetscScalar x, PetscScalar y, PetscScalar t) {
  return (PetscScalar)((1.0/2.0)*M_PI*std::exp(-4.0*std::pow(M_PI, 2)*t)*std::sin(2*M_PI*y));
}

static inline PetscScalar fx_navier_stokes(PetscScalar x, PetscScalar y, PetscScalar t) {
  return (PetscScalar)(0);
}

static inline PetscScalar fy_navier_stokes(PetscScalar x, PetscScalar y, PetscScalar t) {
  return (PetscScalar)(0);
}

} // namespace TAYLOR_GREEN_2D

namespace POISEUILLE_FLOW_2D {
static inline PetscScalar u_exact(PetscScalar x, PetscScalar y, PetscScalar t) {
  return (PetscScalar)(4*y*(1 - y)*std::cos(M_PI*t));
}

static inline PetscScalar v_exact(PetscScalar x, PetscScalar y, PetscScalar t) {
  return (PetscScalar)(0);
}

static inline PetscScalar p_exact(PetscScalar x, PetscScalar y, PetscScalar t) {
  return (PetscScalar)(-8.0*x*std::cos(M_PI*t));
}

static inline PetscScalar fx_heat(PetscScalar x, PetscScalar y, PetscScalar t) {
  return (PetscScalar)(4*M_PI*y*(y - 1)*std::sin(M_PI*t) + 8.0*std::cos(M_PI*t));
}

static inline PetscScalar fy_heat(PetscScalar x, PetscScalar y, PetscScalar t) {
  return (PetscScalar)(0);
}

static inline PetscScalar fx_stokes(PetscScalar x, PetscScalar y, PetscScalar t) {
  return (PetscScalar)(4*M_PI*y*(y - 1)*std::sin(M_PI*t));
}

static inline PetscScalar fy_stokes(PetscScalar x, PetscScalar y, PetscScalar t) {
  return (PetscScalar)(0);
}

static inline PetscScalar fx_navier_stokes(PetscScalar x, PetscScalar y, PetscScalar t) {
  return (PetscScalar)(4*M_PI*y*(y - 1)*std::sin(M_PI*t));
}

static inline PetscScalar fy_navier_stokes(PetscScalar x, PetscScalar y, PetscScalar t) {
  return (PetscScalar)(0);
}

} // namespace POISEUILLE_FLOW_2D


} // namespace STOKES
