// AUTO-GENERATED by tools/stokes.py — DO NOT EDIT BY HAND
#pragma once
#include <cmath>
#include <petscsys.h>

// ============================================================================
// STOKES EQUATION (time-dependent): ∂u/∂t - ν∇²u + ∇p = f,  ∇·u = 0
// Manufactured solution: Taylor–Green vortex (2D)
// nu = 1.0
// ============================================================================
namespace STOKES {

namespace FUNC_2D {
using VELOCITY_EXACT  = PetscScalar (*)(PetscScalar, PetscScalar, PetscScalar);
using PRESSURE_EXACT  = PetscScalar (*)(PetscScalar, PetscScalar, PetscScalar);
using VELOCITY_INITIAL = PetscScalar (*)(PetscScalar, PetscScalar);
using FORCE           = PetscScalar (*)(PetscScalar, PetscScalar, PetscScalar);
} // namespace FUNC_2D

namespace TAYLOR_GREEN_2D {
static inline PetscScalar u_exact(PetscScalar x, PetscScalar y, PetscScalar t) {
  return (PetscScalar)(-std::exp(-2.0*std::pow(M_PI, 2)*t)*std::sin(M_PI*y)*std::cos(M_PI*x));
}

static inline PetscScalar v_exact(PetscScalar x, PetscScalar y, PetscScalar t) {
  return (PetscScalar)(std::exp(-2.0*std::pow(M_PI, 2)*t)*std::sin(M_PI*x)*std::cos(M_PI*y));
}

static inline PetscScalar p_exact(PetscScalar x, PetscScalar y, PetscScalar t) {
  return (PetscScalar)(-1.0/4.0*(std::cos(2*M_PI*x) + std::cos(2*M_PI*y))*std::exp(-4.0*std::pow(M_PI, 2)*t));
}

static inline PetscScalar u_initial(PetscScalar x, PetscScalar y) {
  // t = 0
  return (PetscScalar)(-std::sin(M_PI*y)*std::cos(M_PI*x));
}

static inline PetscScalar v_initial(PetscScalar x, PetscScalar y) {
  // t = 0
  return (PetscScalar)(std::sin(M_PI*x)*std::cos(M_PI*y));
}

static inline PetscScalar fx(PetscScalar x, PetscScalar y, PetscScalar t) {
  return (PetscScalar)((1.0/2.0)*M_PI*std::exp(-4.0*std::pow(M_PI, 2)*t)*std::sin(2*M_PI*x));
}

static inline PetscScalar fy(PetscScalar x, PetscScalar y, PetscScalar t) {
  return (PetscScalar)((1.0/2.0)*M_PI*std::exp(-4.0*std::pow(M_PI, 2)*t)*std::sin(2*M_PI*y));
}

// Optional placeholders for heat module compatibility
static inline PetscScalar fx_heat(PetscScalar, PetscScalar, PetscScalar) { return 0.0; }
static inline PetscScalar fy_heat(PetscScalar, PetscScalar, PetscScalar) { return 0.0; }

} // namespace TAYLOR_GREEN_2D

} // namespace STOKES
