#!/usr/bin/env python3
"""
Generate src/analytical/stokes.h from symbolic definitions of (u, v, p)
for the time-dependent Stokes equations in 2D:

    ∂u/∂t - ν ∇²u + ∇p = f,   ∇·u = 0

Currently supports: Taylor–Green vortex (2D)

Usage examples:
  - Default (Taylor–Green, nu=1.0):
      python tools/stokes.py

  - Custom viscosity and output path:
      python tools/stokes.py --nu 0.5 --out src/analytical/stokes.h

This script requires SymPy: pip install sympy
"""
from __future__ import annotations
import argparse
from pathlib import Path
from typing import Tuple

import sympy as sp
from sympy import ccode

# ------------------------------------------------------------
# Utilities
# ------------------------------------------------------------

def cxx(expr: sp.Expr) -> str:
    """Convert SymPy expr to C++ code string using std:: math functions.
    Ensures usage of M_PI and std::sin/cos/exp.
    """
    s = ccode(sp.simplify(expr), standard='C99')
    # Prefix with std:: for common math funcs; keep M_PI from sympy
    for fn in ["sin", "cos", "exp", "pow", "sqrt"]:
        s = s.replace(f"{fn}(", f"std::{fn}(")
    return s

# ------------------------------------------------------------
# Define manufactured solution (Taylor–Green 2D)
# ------------------------------------------------------------

def taylor_green_2d(nu: float) -> Tuple[sp.Expr, sp.Expr, sp.Expr]:
    x, y, t = sp.symbols('x y t', real=True)
    pi = sp.pi
    nu_sym = sp.Symbol('nu', real=True)

    u = -sp.cos(pi*x) * sp.sin(pi*y) * sp.exp(-2*pi*pi*nu_sym*t)
    v =  sp.sin(pi*x) * sp.cos(pi*y) * sp.exp(-2*pi*pi*nu_sym*t)
    p = -sp.Rational(1,4) * (sp.cos(2*pi*x) + sp.cos(2*pi*y)) * sp.exp(-4*pi*pi*nu_sym*t)

    return (u.subs(nu_sym, nu), v.subs(nu_sym, nu), p.subs(nu_sym, nu))

# ------------------------------------------------------------
# Derive forcing f = (fx, fy)
# ------------------------------------------------------------

def derive_forcing(u: sp.Expr, v: sp.Expr, p: sp.Expr, nu: float) -> Tuple[sp.Expr, sp.Expr]:
    x, y, t = sp.symbols('x y t', real=True)

    # Components: ∂u/∂t - ν ∇²u + ∂p/∂x,  ∂v/∂t - ν ∇²v + ∂p/∂y
    lap_u = sp.diff(u, x, 2) + sp.diff(u, y, 2)
    lap_v = sp.diff(v, x, 2) + sp.diff(v, y, 2)

    fu = sp.diff(u, t) - nu * lap_u + sp.diff(p, x)
    fv = sp.diff(v, t) - nu * lap_v + sp.diff(p, y)

    return sp.simplify(fu), sp.simplify(fv)

# ------------------------------------------------------------
# Render C++ header
# ------------------------------------------------------------

def render_header(u: sp.Expr, v: sp.Expr, p: sp.Expr, fx: sp.Expr, fy: sp.Expr, nu: float) -> str:
    x, y, t = sp.symbols('x y t', real=True)

    # Generate C++ code for each expression
    u_cpp  = cxx(u)
    v_cpp  = cxx(v)
    p_cpp  = cxx(p)
    fx_cpp = cxx(fx)
    fy_cpp = cxx(fy)
    
    # For initial conditions, substitute t=0 before converting to C++
    u_init_cpp = cxx(u.subs(t, 0))
    v_init_cpp = cxx(v.subs(t, 0))

    header = f"""// AUTO-GENERATED by tools/stokes.py — DO NOT EDIT BY HAND
#pragma once
#include <cmath>
#include <petscsys.h>

// ============================================================================
// STOKES EQUATION (time-dependent): ∂u/∂t - ν∇²u + ∇p = f,  ∇·u = 0
// Manufactured solution: Taylor–Green vortex (2D)
// nu = {nu}
// ============================================================================
namespace STOKES {{

namespace FUNC_2D {{
using VELOCITY_EXACT  = PetscScalar (*)(PetscScalar, PetscScalar, PetscScalar);
using PRESSURE_EXACT  = PetscScalar (*)(PetscScalar, PetscScalar, PetscScalar);
using VELOCITY_INITIAL = PetscScalar (*)(PetscScalar, PetscScalar);
using FORCE           = PetscScalar (*)(PetscScalar, PetscScalar, PetscScalar);
}} // namespace FUNC_2D

namespace TAYLOR_GREEN_2D {{
static inline PetscScalar u_exact(PetscScalar x, PetscScalar y, PetscScalar t) {{
  return (PetscScalar)({u_cpp});
}}

static inline PetscScalar v_exact(PetscScalar x, PetscScalar y, PetscScalar t) {{
  return (PetscScalar)({v_cpp});
}}

static inline PetscScalar p_exact(PetscScalar x, PetscScalar y, PetscScalar t) {{
  return (PetscScalar)({p_cpp});
}}

static inline PetscScalar u_initial(PetscScalar x, PetscScalar y) {{
  // t = 0
  return (PetscScalar)({u_init_cpp});
}}

static inline PetscScalar v_initial(PetscScalar x, PetscScalar y) {{
  // t = 0
  return (PetscScalar)({v_init_cpp});
}}

static inline PetscScalar fx(PetscScalar x, PetscScalar y, PetscScalar t) {{
  return (PetscScalar)({fx_cpp});
}}

static inline PetscScalar fy(PetscScalar x, PetscScalar y, PetscScalar t) {{
  return (PetscScalar)({fy_cpp});
}}

// Optional placeholders for heat module compatibility
static inline PetscScalar fx_heat(PetscScalar, PetscScalar, PetscScalar) {{ return 0.0; }}
static inline PetscScalar fy_heat(PetscScalar, PetscScalar, PetscScalar) {{ return 0.0; }}

}} // namespace TAYLOR_GREEN_2D

}} // namespace STOKES
"""
    return header

# ------------------------------------------------------------
# CLI
# ------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(description="Generate src/analytical/stokes.h with manufactured solutions.")
    ap.add_argument('--nu', type=float, default=1.0, help='Kinematic viscosity ν')
    ap.add_argument('--solution', type=str, default='taylor_green_2d', choices=['taylor_green_2d'], help='Manufactured solution to use')
    ap.add_argument('--out', type=Path, default=Path('src/analytical/stokes.h'), help='Output header path')
    args = ap.parse_args()

    # Build solution
    if args.solution == 'taylor_green_2d':
        u, v, p = taylor_green_2d(args.nu)
    else:
        raise NotImplementedError(args.solution)

    fx, fy = derive_forcing(u, v, p, args.nu)

    header = render_header(u, v, p, fx, fy, args.nu)

    out_path: Path = args.out
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(header)
    print(f"Wrote header to: {out_path}")

if __name__ == '__main__':
    main()
