#!/usr/bin/env python3
from __future__ import annotations
import argparse
from pathlib import Path
from typing import Tuple

import sympy as sp
from sympy import ccode

# ==================== Part 1: Reusable header ====================
header_common = """// AUTO-GENERATED by tools/unsteady.py — DO NOT EDIT BY HAND
#pragma once
#include <cmath>
#include <petscsys.h>

// ============================================================================
// FLOW EQUATIONS: Various formulations with manufactured solutions
// Solution: {solution_name}
// nu = {nu}
// ============================================================================
namespace UNSTEADY {{

namespace FUNC_2D {{
using VELOCITY_EXACT  = PetscScalar (*)(PetscScalar, PetscScalar, PetscScalar);
using PRESSURE_EXACT  = PetscScalar (*)(PetscScalar, PetscScalar, PetscScalar);
using FORCE           = PetscScalar (*)(PetscScalar, PetscScalar, PetscScalar);
}} // namespace FUNC_2D

{content}
}} // namespace UNSTEADY
"""

# ==================== Part 2: Solution-specific content ====================
# Template for vector flow solutions (Taylor-Green, Poiseuille, etc.)
solution_content = """namespace {namespace_name} {{
static inline PetscScalar u_exact(PetscScalar x, PetscScalar y, PetscScalar t) {{
  return (PetscScalar)({u_cpp});
}}

static inline PetscScalar v_exact(PetscScalar x, PetscScalar y, PetscScalar t) {{
  return (PetscScalar)({v_cpp});
}}

static inline PetscScalar p_exact(PetscScalar x, PetscScalar y, PetscScalar t) {{
  return (PetscScalar)({p_cpp});
}}

// for poisson equation 
static inline PetscScalar f_poisson(PetscScalar x, PetscScalar y, PetscScalar t) {{
  return (PetscScalar)({f_poisson_cpp});
}}

static inline PetscScalar fx_heat(PetscScalar x, PetscScalar y, PetscScalar t) {{
  return (PetscScalar)({fx_heat_cpp});
}}

static inline PetscScalar fy_heat(PetscScalar x, PetscScalar y, PetscScalar t) {{
  return (PetscScalar)({fy_heat_cpp});
}}

static inline PetscScalar fx_stokes(PetscScalar x, PetscScalar y, PetscScalar t) {{
  return (PetscScalar)({fx_stokes_cpp});
}}

static inline PetscScalar fy_stokes(PetscScalar x, PetscScalar y, PetscScalar t) {{
  return (PetscScalar)({fy_stokes_cpp});
}}

static inline PetscScalar fx_navier_stokes(PetscScalar x, PetscScalar y, PetscScalar t) {{
  return (PetscScalar)({fx_ns_cpp});
}}

static inline PetscScalar fy_navier_stokes(PetscScalar x, PetscScalar y, PetscScalar t) {{
  return (PetscScalar)({fy_ns_cpp});
}}

}} // namespace {namespace_name}

"""

# Template for scalar manufactured solutions (sinpi, poly2, etc.)
# Used by: Poisson (vertex/cell/staggered), Heat (vertex/cell/staggered)
scalar_content = """namespace {namespace_name} {{

// Steady-state: u(x,y) = sin(pi*x) * sin(pi*y)
static inline PetscScalar u_steady(PetscScalar x, PetscScalar y) {{
  return (PetscScalar)({u_steady_cpp});
}}

// Time-dependent: u(x,y,t,alpha) = exp(-2*pi^2*alpha*t) * sin(pi*x) * sin(pi*y)
static inline PetscScalar u_exact(PetscScalar x, PetscScalar y, PetscScalar t, PetscScalar alpha) {{
  (void)alpha; // alpha appears only symbolically below
  return (PetscScalar)({u_cpp});
}}

// Source term for Poisson: f = -Laplacian(u) = 2*pi^2*sin(pi*x)*sin(pi*y)
static inline PetscScalar f_poisson(PetscScalar x, PetscScalar y) {{
  return (PetscScalar)({f_poisson_cpp});
}}

// x-derivative: du/dx = pi*cos(pi*x)*sin(pi*y)  (for staggered/mixed formulation)
static inline PetscScalar gx_exact(PetscScalar x, PetscScalar y) {{
  return (PetscScalar)({gx_cpp});
}}

// y-derivative: du/dy = pi*sin(pi*x)*cos(pi*y)  (for staggered/mixed formulation)
static inline PetscScalar gy_exact(PetscScalar x, PetscScalar y) {{
  return (PetscScalar)({gy_cpp});
}}

// Source term for heat equation: f = du/dt - alpha*Laplacian(u) = 0
static inline PetscScalar f_heat(PetscScalar x, PetscScalar y, PetscScalar t) {{
  return (PetscScalar)({f_heat_cpp});
}}

// Laplacian: Delta(u) = -2*pi^2*sin(pi*x)*sin(pi*y)  (useful for BC checks)
static inline PetscScalar laplacian_u(PetscScalar x, PetscScalar y) {{
  return (PetscScalar)({lap_cpp});
}}

}} // namespace {namespace_name}

"""

def cxx(expr: sp.Expr) -> str:
    s = ccode(sp.simplify(expr), standard='C99')
    for fn in ["sin", "cos", "exp", "pow", "sqrt"]:
        s = s.replace(f"{fn}(", f"std::{fn}(")
    return s

def taylor_green_2d(nu: float) -> Tuple[sp.Expr, sp.Expr, sp.Expr]:
    x, y, t = sp.symbols('x y t', real=True)
    pi = sp.pi
    nu_sym = sp.Symbol('nu', real=True)

    u = -sp.cos(pi*x) * sp.sin(pi*y) * sp.exp(-2*pi*pi*nu_sym*t)
    v =  sp.sin(pi*x) * sp.cos(pi*y) * sp.exp(-2*pi*pi*nu_sym*t)
    p = -sp.Rational(1,4) * (sp.cos(2*pi*x) + sp.cos(2*pi*y)) * sp.exp(-4*pi*pi*nu_sym*t)

    return (u.subs(nu_sym, nu), v.subs(nu_sym, nu), p.subs(nu_sym, nu))

def poiseuille_flow_2d(nu: float) -> Tuple[sp.Expr, sp.Expr, sp.Expr]:
    x, y, t = sp.symbols('x y t', real=True)
    u = 4 * y * (1 - y) * sp.cos(sp.pi * t)
    v = sp.Integer(0) 
    p = -8 * nu * x * sp.cos(sp.pi * t)
    return (u, v, p)

def sinpi_scalar_2d() -> dict:
    """Scalar manufactured solution u(x,y,t) = exp(-2π²αt) sin(πx) sin(πy)
    Satisfies homogeneous Dirichlet BC on all boundaries.
    Alpha is kept symbolic — caller passes it at runtime.
    Returns a dict of all derived quantities."""
    x, y, t = sp.symbols('x y t', real=True)
    pi = sp.pi
    a = sp.Symbol('alpha', real=True)

    u = sp.exp(-2*pi*pi*a*t) * sp.sin(pi*x) * sp.sin(pi*y)
    u_steady = sp.sin(pi*x) * sp.sin(pi*y)

    # Poisson source: f = -Laplacian(u_steady)
    lap_u = sp.diff(u_steady, x, 2) + sp.diff(u_steady, y, 2)
    f_poisson = sp.simplify(-lap_u)

    # Gradients
    gx = sp.simplify(sp.diff(u_steady, x))
    gy = sp.simplify(sp.diff(u_steady, y))

    # Heat source: f = du/dt - alpha*Laplacian(u)
    f_heat = sp.simplify(sp.diff(u, t) - a * (sp.diff(u, x, 2) + sp.diff(u, y, 2)))

    # Laplacian of steady solution
    lap_steady = sp.simplify(sp.diff(u_steady, x, 2) + sp.diff(u_steady, y, 2))

    return {
        'u_steady': u_steady,
        'u': u,
        'f_poisson': f_poisson,
        'gx': gx,
        'gy': gy,
        'f_heat': f_heat,
        'lap': lap_steady,
    }

def derive_source_poisson(p: sp.Expr) -> sp.Expr:
    x, y = sp.symbols('x y', real=True)
    # -Laplacian(p) = f
    lap_p = sp.diff(p, x, 2) + sp.diff(p, y, 2)
    return sp.simplify(-lap_p)

def check_divergence_free(u: sp.Expr, v: sp.Expr):
    x, y = sp.symbols('x y', real=True)
    div = sp.diff(u, x) + sp.diff(v, y)
    simplified_div = sp.simplify(div)
    if simplified_div != 0:
        raise ValueError(f"Velocity field is not divergence free: {simplified_div}")
    print("Check: Velocity field is divergence free.")

def derive_source_heat(u: sp.Expr, v: sp.Expr, p: sp.Expr, nu: float) -> Tuple[sp.Expr, sp.Expr]:
    x, y, t = sp.symbols('x y t', real=True)

    lap_u = sp.diff(u, x, 2) + sp.diff(u, y, 2)
    lap_v = sp.diff(v, x, 2) + sp.diff(v, y, 2)

    fu = sp.diff(u, t) - nu * lap_u
    fv = sp.diff(v, t) - nu * lap_v

    return sp.simplify(fu), sp.simplify(fv)

def derive_source_stokes(u: sp.Expr, v: sp.Expr, p: sp.Expr, nu: float) -> Tuple[sp.Expr, sp.Expr]:
    x, y, t = sp.symbols('x y t', real=True)

    lap_u = sp.diff(u, x, 2) + sp.diff(u, y, 2)
    lap_v = sp.diff(v, x, 2) + sp.diff(v, y, 2)

    fu = sp.diff(u, t) - nu * lap_u + sp.diff(p, x)
    fv = sp.diff(v, t) - nu * lap_v + sp.diff(p, y)

    return sp.simplify(fu), sp.simplify(fv)

def derive_source_navier_stokes(u: sp.Expr, v: sp.Expr, p: sp.Expr, nu: float) -> Tuple[sp.Expr, sp.Expr]:
    x, y, t = sp.symbols('x y t', real=True)

    lap_u = sp.diff(u, x, 2) + sp.diff(u, y, 2)
    lap_v = sp.diff(v, x, 2) + sp.diff(v, y, 2)

    conv_u = u * sp.diff(u, x) + v * sp.diff(u, y)
    conv_v = u * sp.diff(v, x) + v * sp.diff(v, y)

    fu = sp.diff(u, t) + conv_u - nu * lap_u + sp.diff(p, x)
    fv = sp.diff(v, t) + conv_v - nu * lap_v + sp.diff(p, y)

    return sp.simplify(fu), sp.simplify(fv)

def main():
    ap = argparse.ArgumentParser(description="Generate src/analytical/unsteady.h with manufactured solutions.")
    ap.add_argument('--nu', type=float, default=1.0, help='Kinematic viscosity nu')
    ap.add_argument('--out', type=Path, default=Path('src/analytical/unsteady.h'), help='Output header path')
    args = ap.parse_args()

    # ==================== Solution 1: Taylor-Green Vortex ====================
    u1, v1, p1 = taylor_green_2d(args.nu)
    check_divergence_free(u1, v1)
    f_poisson_1 = derive_source_poisson(p1)
    fx_heat_1, fy_heat_1 = derive_source_heat(u1, v1, p1, args.nu)
    fx_stokes_1, fy_stokes_1 = derive_source_stokes(u1, v1, p1, args.nu)
    fx_ns_1, fy_ns_1 = derive_source_navier_stokes(u1, v1, p1, args.nu)
    
    content_taylor = solution_content.format(
        namespace_name="TAYLOR_GREEN_2D",
        u_cpp=cxx(u1),
        v_cpp=cxx(v1),
        p_cpp=cxx(p1),
        f_poisson_cpp=cxx(f_poisson_1),
        fx_heat_cpp=cxx(fx_heat_1),
        fy_heat_cpp=cxx(fy_heat_1),
        fx_stokes_cpp=cxx(fx_stokes_1),
        fy_stokes_cpp=cxx(fy_stokes_1),
        fx_ns_cpp=cxx(fx_ns_1),
        fy_ns_cpp=cxx(fy_ns_1)
    )

    # # ==================== Solution 2: Poiseuille Flow ====================
    # u2, v2, p2 = poiseuille_flow_2d(args.nu)

    # ==================== Solution 2: Scalar Sinpi (for Poisson & Heat) ====================
    sinpi = sinpi_scalar_2d()  # alpha kept as symbolic parameter
    content_sinpi = scalar_content.format(
        namespace_name="SINPI_SCALAR_2D",
        u_steady_cpp=cxx(sinpi['u_steady']),
        u_cpp=cxx(sinpi['u']),
        f_poisson_cpp=cxx(sinpi['f_poisson']),
        gx_cpp=cxx(sinpi['gx']),
        gy_cpp=cxx(sinpi['gy']),
        f_heat_cpp=cxx(sinpi['f_heat']),
        lap_cpp=cxx(sinpi['lap']),
    )

    # ==================== Combine all solutions ====================
    combined_content = content_taylor + content_sinpi
    
    header = header_common.format(
        content=combined_content,
        solution_name="Taylor-Green vortex (2D) + Scalar Sinpi (2D)",
        nu=args.nu
    )

    out_path: Path = args.out
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(header)
    print(f"Wrote header to: {out_path}")
    print(f"Solutions included: Taylor-Green vortex + Poiseuille flow, nu={args.nu}")

if __name__ == '__main__':
    main()
